# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


import typing
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMainWindow, QWidget,QApplication


class CalcWindow(QMainWindow):
    
    def __init__(self) -> None:
        super().__init__()
        self.setupUi(self)
        self.btnOne.clicked.connect(lambda x:self.btns_clicked('1'))
        self.btnTwo.clicked.connect(lambda x:self.btns_clicked('2'))
        self.btnThree.clicked.connect(lambda x:self.btns_clicked('3'))
        self.btnFour.clicked.connect(lambda x:self.btns_clicked('4'))
        self.btnFive.clicked.connect(lambda x:self.btns_clicked('5'))
        self.btnSix.clicked.connect(lambda x:self.btns_clicked('6'))
        self.btnSeven.clicked.connect(lambda x:self.btns_clicked('7'))
        self.btnEight.clicked.connect(lambda x:self.btns_clicked('8'))
        self.btnNine_2.clicked.connect(lambda x:self.btns_clicked('9'))
        self.btnZero.clicked.connect(lambda x:self.btns_clicked('0'))
        self.btnPlus.clicked.connect(lambda x:self.btns_clicked('+'))
        self.btnMinus.clicked.connect(lambda x:self.btns_clicked('-'))
        self.btnMul.clicked.connect(lambda x:self.btns_clicked('*'))
        self.btnDiv.clicked.connect(lambda x:self.btns_clicked('/'))
        self.btnEqual.clicked.connect(lambda x:self.btns_clicked('='))
        self.btnDot.clicked.connect(lambda x:self.btns_clicked('.'))
        self.btnClear.clicked.connect(lambda x:self.btns_clicked('C'))

    def btns_clicked(self, b:str):
        if b == '=':
             ans = eval(self.lineEdit.text())
             self.lineEdit.setText(str(ans))
        elif b == 'C':
             ans = str(self.lineEdit.text())
             self.lineEdit.setText(ans[:-1])
        else:
                self.lineEdit.setText(self.lineEdit.text()+b)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(477, 540)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setMaximumSize(QtCore.QSize(350, 55))
        self.lineEdit.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_5.addWidget(self.lineEdit)
        self.btnClear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnClear.setMinimumSize(QtCore.QSize(45, 45))
        self.btnClear.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnClear.setFont(font)
        self.btnClear.setAutoFillBackground(False)
        self.btnClear.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(15, 15, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(85, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 9px\n"
"}")
        self.btnClear.setObjectName("btnClear")
        self.horizontalLayout_5.addWidget(self.btnClear)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnNine_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnNine_2.setMinimumSize(QtCore.QSize(45, 45))
        self.btnNine_2.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnNine_2.setFont(font)
        self.btnNine_2.setAutoFillBackground(False)
        self.btnNine_2.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(15, 15, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(85, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 9px\n"
"}")
        self.btnNine_2.setObjectName("btnNine_2")
        self.horizontalLayout.addWidget(self.btnNine_2)
        self.btnEight = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnEight.setMinimumSize(QtCore.QSize(45, 45))
        self.btnEight.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnEight.setFont(font)
        self.btnEight.setAutoFillBackground(False)
        self.btnEight.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(15, 15, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(85, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 9px\n"
"}")
        self.btnEight.setObjectName("btnEight")
        self.horizontalLayout.addWidget(self.btnEight)
        self.btnSeven = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSeven.setMinimumSize(QtCore.QSize(45, 45))
        self.btnSeven.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnSeven.setFont(font)
        self.btnSeven.setAutoFillBackground(False)
        self.btnSeven.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(15, 15, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(85, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 9px\n"
"}")
        self.btnSeven.setObjectName("btnSeven")
        self.horizontalLayout.addWidget(self.btnSeven)
        self.btnDiv = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDiv.setMinimumSize(QtCore.QSize(45, 45))
        self.btnDiv.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnDiv.setFont(font)
        self.btnDiv.setAutoFillBackground(False)
        self.btnDiv.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(15, 15, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(85, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 9px\n"
"}")
        self.btnDiv.setObjectName("btnDiv")
        self.horizontalLayout.addWidget(self.btnDiv)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnSix = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSix.setMinimumSize(QtCore.QSize(45, 45))
        self.btnSix.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnSix.setFont(font)
        self.btnSix.setAutoFillBackground(False)
        self.btnSix.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(15, 15, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(85, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 9px\n"
"}")
        self.btnSix.setObjectName("btnSix")
        self.horizontalLayout_2.addWidget(self.btnSix)
        self.btnFive = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnFive.setMinimumSize(QtCore.QSize(45, 45))
        self.btnFive.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnFive.setFont(font)
        self.btnFive.setAutoFillBackground(False)
        self.btnFive.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(15, 15, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(85, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 9px\n"
"}")
        self.btnFive.setObjectName("btnFive")
        self.horizontalLayout_2.addWidget(self.btnFive)
        self.btnFour = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnFour.setMinimumSize(QtCore.QSize(45, 45))
        self.btnFour.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnFour.setFont(font)
        self.btnFour.setAutoFillBackground(False)
        self.btnFour.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(15, 15, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(85, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 9px\n"
"}")
        self.btnFour.setObjectName("btnFour")
        self.horizontalLayout_2.addWidget(self.btnFour)
        self.btnMul = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnMul.setMinimumSize(QtCore.QSize(45, 45))
        self.btnMul.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnMul.setFont(font)
        self.btnMul.setAutoFillBackground(False)
        self.btnMul.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(15, 15, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(85, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 9px\n"
"}")
        self.btnMul.setObjectName("btnMul")
        self.horizontalLayout_2.addWidget(self.btnMul)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnThree = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnThree.setMinimumSize(QtCore.QSize(45, 45))
        self.btnThree.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnThree.setFont(font)
        self.btnThree.setAutoFillBackground(False)
        self.btnThree.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(15, 15, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(85, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 9px\n"
"}")
        self.btnThree.setObjectName("btnThree")
        self.horizontalLayout_3.addWidget(self.btnThree)
        self.btnTwo = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnTwo.setMinimumSize(QtCore.QSize(45, 45))
        self.btnTwo.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnTwo.setFont(font)
        self.btnTwo.setAutoFillBackground(False)
        self.btnTwo.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(15, 15, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(85, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 9px\n"
"}")
        self.btnTwo.setObjectName("btnTwo")
        self.horizontalLayout_3.addWidget(self.btnTwo)
        self.btnOne = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnOne.setMinimumSize(QtCore.QSize(45, 45))
        self.btnOne.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnOne.setFont(font)
        self.btnOne.setAutoFillBackground(False)
        self.btnOne.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(15, 15, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(85, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 9px\n"
"}")
        self.btnOne.setObjectName("btnOne")
        self.horizontalLayout_3.addWidget(self.btnOne)
        self.btnPlus = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnPlus.setMinimumSize(QtCore.QSize(45, 45))
        self.btnPlus.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnPlus.setFont(font)
        self.btnPlus.setAutoFillBackground(False)
        self.btnPlus.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(15, 15, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(85, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 9px\n"
"}")
        self.btnPlus.setObjectName("btnPlus")
        self.horizontalLayout_3.addWidget(self.btnPlus)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnZero = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnZero.setMinimumSize(QtCore.QSize(45, 45))
        self.btnZero.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnZero.setFont(font)
        self.btnZero.setAutoFillBackground(False)
        self.btnZero.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(15, 15, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(85, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 9px\n"
"}")
        self.btnZero.setObjectName("btnZero")
        self.horizontalLayout_4.addWidget(self.btnZero)
        self.btnDot = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDot.setMinimumSize(QtCore.QSize(45, 45))
        self.btnDot.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnDot.setFont(font)
        self.btnDot.setAutoFillBackground(False)
        self.btnDot.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(15, 15, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(85, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 9px\n"
"}")
        self.btnDot.setObjectName("btnDot")
        self.horizontalLayout_4.addWidget(self.btnDot)
        self.btnEqual = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnEqual.setMinimumSize(QtCore.QSize(45, 45))
        self.btnEqual.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnEqual.setFont(font)
        self.btnEqual.setAutoFillBackground(False)
        self.btnEqual.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(15, 15, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(85, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 9px\n"
"}")
        self.btnEqual.setObjectName("btnEqual")
        self.horizontalLayout_4.addWidget(self.btnEqual)
        self.btnMinus = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnMinus.setMinimumSize(QtCore.QSize(45, 45))
        self.btnMinus.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnMinus.setFont(font)
        self.btnMinus.setAutoFillBackground(False)
        self.btnMinus.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(15, 15, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(85, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 9px\n"
"}")
        self.btnMinus.setObjectName("btnMinus")
        self.horizontalLayout_4.addWidget(self.btnMinus)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 477, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.CalcWindow = QtWidgets.QMenu(parent=self.menubar)
        self.CalcWindow.setMinimumSize(QtCore.QSize(300, 300))
        self.CalcWindow.setMaximumSize(QtCore.QSize(400, 400))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CalcWindow.setFont(font)
        self.CalcWindow.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.CalcWindow.setObjectName("CalcWindow")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icon/balance-sheet.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtGui.QAction(parent=MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.CalcWindow.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NajotCalc"))
        self.btnClear.setText(_translate("MainWindow", "C"))
        self.btnNine_2.setText(_translate("MainWindow", "9"))
        self.btnEight.setText(_translate("MainWindow", "8"))
        self.btnSeven.setText(_translate("MainWindow", "7"))
        self.btnDiv.setText(_translate("MainWindow", "/"))
        self.btnSix.setText(_translate("MainWindow", "6"))
        self.btnFive.setText(_translate("MainWindow", "5"))
        self.btnFour.setText(_translate("MainWindow", "4"))
        self.btnMul.setText(_translate("MainWindow", "*"))
        self.btnThree.setText(_translate("MainWindow", "3"))
        self.btnTwo.setText(_translate("MainWindow", "2"))
        self.btnOne.setText(_translate("MainWindow", "1"))
        self.btnPlus.setText(_translate("MainWindow", "+"))
        self.btnZero.setText(_translate("MainWindow", "0"))
        self.btnDot.setText(_translate("MainWindow", "."))
        self.btnEqual.setText(_translate("MainWindow", "="))
        self.btnMinus.setText(_translate("MainWindow", "-"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.CalcWindow.setTitle(_translate("MainWindow", "About"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

